## Import de module

In [1]:
import tensorflow as tf
from tensorflow.python.client import device_lib

In [2]:
from os import path
from time import time

In [3]:
import numpy as np

## Création de variables d'environnement

In [4]:
tf.test.gpu_device_name()

'/device:GPU:0'

In [5]:
accelerator = 'cu80' if path.exists('/opt/bin/nvidia-smi') else 'cpu'

In [6]:
accelerator

'cu80'

In [7]:
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 9093936707024397000
 xla_global_id: -1, name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 16154099712
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 11847872877822588417
 physical_device_desc: "device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0"
 xla_global_id: 416903419]

In [8]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.8.0


## Utilisation des tenseurs

In [9]:
# This will be an int32 tensor by default; see "dtypes" below.
rank_0_tensor = tf.constant(4)

In [10]:
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [11]:
# Let's make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])

In [12]:
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [13]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)

In [14]:
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [15]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

In [16]:
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [17]:
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [18]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [19]:
a = tf.constant([
                 [1,2],
                 [3,4]
                 ])

In [20]:
b = tf.constant([
                 [1,1],
                 [1,1]
                 ])

In [21]:
print(tf.add(a, b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [22]:
print(tf.multiply(a,b))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [23]:
print(tf.matmul(a, b))

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [24]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [25]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))

# Find the index of the largest value
print(tf.argmax(c))

# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105854e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


## A propos des shapes
Les tenseurs ont des shapes. Un peu de vocabulaire :

`shape` : La longueur (nombre d'éléments) de chacun des axes d'un tenseur.

`Rank` : Nombre d'axes du tenseur. Un scalaire a le rang 0, un vecteur le rang 1, une matrice le rang 2.

`Axe` ou `dimension` : Une dimension particulière d'un tenseur.

`Taille` : Le nombre total d'éléments dans le tenseur, le produit vecteur de forme.

In [26]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

In [27]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


## Indexation
Indexation à axe unique
TensorFlow suit les règles d'indexation standard de Python, similaires à l'indexation d'une liste ou d'une chaîne de caractères en Python, et les règles de base de l'indexation de NumPy.

les index commencent à 0
les indices négatifs comptent à rebours à partir de la fin
les deux points, :, sont utilisés pour les tranches : start:stop:step

In [28]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


In [29]:
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

First: 0
Second: 1
Last: 34


In [30]:
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


In [31]:
print("From start to end", rank_1_tensor[:-1].numpy())
print("Start to start", rank_1_tensor[1:].numpy())
print("Start to start and stop", rank_1_tensor[1:-2].numpy())

From start to end [ 0  1  1  2  3  5  8 13 21]
Start to start [ 1  1  2  3  5  8 13 21 34]
Start to start and stop [ 1  1  2  3  5  8 13]


## Multi-indexing
Les tenseurs de rang supérieur sont indexés en passant des indices multiples.

Les mêmes règles que dans le cas d'un axe unique s'appliquent à chaque axe indépendamment.

In [32]:
print(rank_2_tensor.numpy())

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [33]:
# Pull out a single value from a 2-rank tensor
print(rank_2_tensor[1, 1].numpy())

4.0


In [34]:
print(rank_2_tensor[0:, 1:].numpy())

[[2.]
 [4.]
 [6.]]


In [35]:
# Get row and column tensors
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

Second row: [3. 4.]
Second column: [2. 4. 6.]
Last row: [5. 6.]
First item in last column: 2.0
Skip the first row:
[[3. 4.]
 [5. 6.]] 



In [36]:
print(rank_3_tensor[:, :, 4].numpy())

[[ 4  9]
 [14 19]
 [24 29]]


## Gestion du temps d'execution
Gestion du temps d'execution entre un `numpy.array()`, une `list()` et un `tensor` avec et sans GPU.

In [37]:
list_1 = list(range(1000))

In [38]:
lnp = np.array(list_1)

In [39]:
%%timeit
lp2 = []
for i in list_1:
  lp2.append(2 * i)

1000 loops, best of 5: 236 µs per loop


In [40]:
%%timeit
lst = [i * 2 for i in list_1]

10000 loops, best of 5: 149 µs per loop


In [41]:
%%timeit
lnp2 = 2 * list_1

100000 loops, best of 5: 10.1 µs per loop


In [42]:
t0 = time()
t1 = time()
print(t0 - t1)

-4.649162292480469e-05


In [43]:
# print(t0 - t1)

In [44]:
A = np.random.rand(1000,1000)
B = np.random.rand(1000,1000)

In [45]:
t0 = time()
C = A @ B
t1 = time()
print(t1 - t0)

0.1446547508239746


In [46]:
A2 = tf.convert_to_tensor(np.random.rand(1000,1000))
B2 = tf.convert_to_tensor(np.random.rand(1000,1000))

In [47]:
t0 = time()
C2 = A2 @ B2
t1 = time()
print(t1 - t0)

1.8196816444396973


In [48]:
Afloat = np.random.rand(1000,1000).astype('float32')
Bfloat = np.random.rand(1000,1000).astype('float32')

In [49]:
t0 = time()
C3 = Afloat @ Bfloat
t1 = time()
print(t1 - t0)

0.03546929359436035


## Manipulation des shapes
Remodeler un tenseur est d'une grande utilité.

In [50]:
# Shape returns a `TensorShape` object that shows the size along each axis
x = tf.constant([[1], [2], [3]])

In [51]:
print(x.shape)

(3, 1)


In [52]:
print(x.shape.as_list())

[3, 1]


In [53]:
# You can reshape a tensor to a new shape.
# Note that you're passing in a list
reshaped = tf.reshape(x, [1, 3])

In [54]:
print(x.shape)

(3, 1)


In [55]:
print(reshaped.shape)

(1, 3)


In [56]:
# A `-1` passed in the `shape` argument says "Whatever fits".
print(tf.reshape(rank_3_tensor, [-1]).numpy())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [57]:
print(tf.reshape(rank_3_tensor, [3*2, 5]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)


In [58]:
print(tf.reshape(rank_3_tensor, [3, -1]))

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


In [59]:
# Bad examples: don't do this

# You can't reorder axes with reshape.
print(tf.reshape(rank_3_tensor, [2, 3, 5]), "\n") 

# This is a mess
print(tf.reshape(rank_3_tensor, [5, 6]), "\n")

# This doesn't work at all
try:
  tf.reshape(rank_3_tensor, [7, -1])
except Exception as e:
  print(f"{type(e).__name__}: {e}")

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]], shape=(5, 6), dtype=int32) 

InvalidArgumentError: Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7 [Op:Reshape]


## Plus sur les DTypes
Pour inspecter le type de données d'un `tf.Tensor`, utilisez la propriété `Tensor.dtype`.

Lorsque vous créez un `tf.Tensor` à partir d'un objet Python, vous pouvez éventuellement spécifier le type de données.

Si vous ne le faites pas, TensorFlow choisit un type de données qui peut représenter vos données. 

TensorFlow convertit les entiers Python en `tf.int32` et les nombres à virgule flottante Python en `tf.float32`. 

Sinon, TensorFlow utilise les mêmes règles que NumPy pour la conversion en tableaux.

Vous pouvez effectuer des castings de type à type.


In [60]:
the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)

the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)

the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)

In [61]:
print(the_f64_tensor)

tf.Tensor([2.2 3.3 4.4], shape=(3,), dtype=float64)


In [62]:
print(the_f16_tensor)

tf.Tensor([2.2 3.3 4.4], shape=(3,), dtype=float16)


In [63]:
# Now, cast to an uint8 and lose the decimal precision
print(the_u8_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=uint8)


## Broadcasting
Le `broadcasting` ou la `diffusion` en français, est un concept emprunté à la fonction équivalente de NumPy. 

En bref, sous certaines conditions, les petits tenseurs sont `étirés` automatiquement pour s'adapter aux grands tenseurs lors de l'exécution d'opérations combinées sur eux.

Le cas le plus simple et le plus courant est celui où vous tentez de multiplier ou d'ajouter un tenseur à un scalaire. Dans ce cas, le scalaire est diffusé pour avoir la même forme que l'autre argument

In [64]:
x = tf.constant([1, 2, 3])
y = tf.constant(2)
z = tf.constant([2, 2, 2])

In [65]:
# All of these are the same computation
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


De même, les axes de longueur 1 peuvent être étirés pour correspondre aux autres arguments. Les deux arguments peuvent être étirés dans le même calcul.

Dans ce cas, une matrice 3x1 est multipliée par éléments par une matrice 1x4 pour produire une matrice 3x4. Notez que le 1 de tête est facultatif : La forme de y est [4].

In [66]:
# These are the same computations
x = tf.reshape(x,[3,1])
y = tf.range(1, 5)

In [67]:
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [68]:
x_stretch = tf.constant([[1, 1, 1, 1],
                         [2, 2, 2, 2],
                         [3, 3, 3, 3]])

y_stretch = tf.constant([[1, 2, 3, 4],
                         [1, 2, 3, 4],
                         [1, 2, 3, 4]])

In [69]:
print(x_stretch * y_stretch)  # Again, operator overloading

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [70]:
print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


Contrairement à une opération mathématique, par exemple, `broadcast_to` ne fait rien de spécial pour économiser de la mémoire. 
Ici, vous matérialisez le tenseur.
Cela peut devenir encore plus compliqué. Cette section du livre Python Data Science Handbook de Jake VanderPlas présente d'autres astuces de diffusion (toujours en NumPy).

## `tf.convert_to_tensor`

La plupart des opérations, comme `tf.matmul` et `tf.reshape` prennent des arguments de la classe `tf.Tensor`.

Cependant, vous remarquerez que dans le cas ci-dessus, les objets Python ayant la forme de tenseurs sont acceptés.

La plupart des opérations, mais pas toutes, appellent `convert_to_tensor` sur des arguments non tenseurs. Il existe un registre de conversions, et la plupart des classes d'objets comme NumPy's `ndarray`, `TensorShape`, les listes Python, et `tf.Variable` seront toutes converties automatiquement.

Voir `tf.register_tensor_conversion_function pour plus de détails, et si vous avez votre propre type que vous souhaitez convertir automatiquement en tenseur.



### Ragged Tensors
Un tenseur avec un nombre variable d'éléments le long d'un axe est appelé `ragged`. 

Utilisez `tf.ragged.RaggedTensor` pour les données irrégulières.

Par exemple, Ceci ne peut pas être représenté comme un tenseur régulier :

In [71]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]
]

In [72]:
try:
  tensor = tf.constant(ragged_list)
except Exception as e:
  print(f"{type(e).__name__}: {e}")

ValueError: Can't convert non-rectangular Python sequence to Tensor.


Créez plutôt un `tf.RaggedTensor` en utilisant `tf.ragged.constant` :

In [73]:
ragged_tensor = tf.ragged.constant(ragged_list)

In [80]:
print(ragged_tensor.shape, "\n")
print(ragged_tensor)

(4, None) 

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


## Tenseurs de chaînes de caractères
`tf.string` est un dtype, c'est-à-dire que vous pouvez représenter des données sous forme de chaînes (tableaux d'octets de longueur variable) dans des tenseurs.

Les chaînes de caractères sont atomiques et ne peuvent pas être indexées comme le sont les chaînes de caractères Python. La longueur de la chaîne n'est pas un des axes du tenseur. Voir tf.strings pour les fonctions permettant de les manipuler.

Voici un tenseur de chaînes scalaires :

In [81]:
# Tensors can be strings, too here is a scalar string.
scalar_string_tensor = tf.constant("Teen Wolf")

In [82]:
print(scalar_string_tensor)

tf.Tensor(b'Teen Wolf', shape=(), dtype=string)


In [83]:
# If you have three string tensors of different lengths, this is OK.
tensor_of_strings = tf.constant(["Teen wolf",
                                 "Quick red fox",
                                 "Lazy cat"])

In [84]:
# Note that the shape is (3,). The string length is not included.
print(tensor_of_strings)

tf.Tensor([b'Teen wolf' b'Quick red fox' b'Lazy cat'], shape=(3,), dtype=string)


Dans l'impression ci-dessus, le préfixe b indique que le dtype `tf.string` n'est pas une chaîne unicode, mais une chaîne d'octets. Consultez le Tutoriel Unicode pour en savoir plus sur le travail avec du texte unicode dans TensorFlow.

Si vous passez des caractères unicode, ils sont encodés en utf-8.

In [85]:
tf.constant("🥳👍")

<tf.Tensor: shape=(), dtype=string, numpy=b'\xf0\x9f\xa5\xb3\xf0\x9f\x91\x8d'>

In [86]:
# You can use split to split a string into a set of tensors
print(tf.strings.split(scalar_string_tensor, sep=" "))

tf.Tensor([b'Teen' b'Wolf'], shape=(2,), dtype=string)


In [87]:
# ...but it turns into a `RaggedTensor` if you split up a tensor of strings,
# as each string might be split into a different number of parts.
print(tf.strings.split(tensor_of_strings))

<tf.RaggedTensor [[b'Teen', b'wolf'], [b'Quick', b'red', b'fox'], [b'Lazy', b'cat']]>


In [88]:
text = tf.constant("1 10 100")

In [91]:
print(tf.strings.to_number(tf.strings.split(text, " ")))

tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


Bien que vous ne puissiez pas utiliser `tf.cast` pour transformer un tenseur de chaînes en nombres, vous pouvez le convertir en octets, puis en nombres.

In [92]:
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)

In [94]:
print("Byte strings:", byte_strings)
print("\nBytes:", byte_ints)

Byte strings: tf.Tensor([b'D' b'u' b'c' b'k'], shape=(4,), dtype=string)

Bytes: tf.Tensor([ 68 117  99 107], shape=(4,), dtype=uint8)


In [95]:
unicode_bytes = tf.constant("アヒル 🦆")
unicode_char_bytes = tf.strings.unicode_split(unicode_bytes, "UTF-8")
unicode_values = tf.strings.unicode_decode(unicode_bytes, "UTF-8")

In [96]:
print("\nUnicode bytes:", unicode_bytes)
print("\nUnicode chars:", unicode_char_bytes)
print("\nUnicode values:", unicode_values)


Unicode bytes: tf.Tensor(b'\xe3\x82\xa2\xe3\x83\x92\xe3\x83\xab \xf0\x9f\xa6\x86', shape=(), dtype=string)

Unicode chars: tf.Tensor([b'\xe3\x82\xa2' b'\xe3\x83\x92' b'\xe3\x83\xab' b' ' b'\xf0\x9f\xa6\x86'], shape=(5,), dtype=string)

Unicode values: tf.Tensor([ 12450  12498  12523     32 129414], shape=(5,), dtype=int32)


Le dtype `tf.string` est utilisé pour toutes les données brutes en octets dans TensorFlow. 

Le module `tf.io` contient des fonctions permettant de convertir des données en octets ou à partir d'octets, y compris le décodage d'images et l'analyse syntaxique de données csv.

## Sparse tensors
Parfois, vos données sont éparses, comme un espace d'intégration très large. 

TensorFlow supporte `tf.sparse.SparseTensor` et les opérations associées pour stocker efficacement les données éparses.

In [97]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])

In [98]:
print(sparse_tensor, "\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
